### PR TITLE
Add authorization with Pundit

### PR DESCRIPTION
**Pull request by zamith**
First of all, sorry for the long PR, but I ended adding the authorization for
everything at once.

Why:
- There were a lot of endpoints exposed to the public that shouldn't be, which
  was a big security flaw.

This change addresses the need by:
- _Hiding_ a fair amount of endpoint behind Devise's `authenticated` route
  constraint, ensuring that if you're not signed in you'll get a 404 for all
  routes that are not open to the public. This includes guests.
- Adding Pundit to every controller, making sure that authorization is done for
  every action except `index`, in which we expect a policy scope. A policy scope
  is pretty much saying that a certain user only has access to a certain part
  of the entire dataset you're listing in that `index` action. This follows the
  Pundit specs, which you can find [here](https://github.com/elabs/pundit#ensuring-policies-and-scopes-are-used).
- Ensuring that Pundit fails the authorization if there is not user. In
  practical terms these is a double check on the authenticated constraint, and no
  real user should be able to hit these endpoints.
- Keeping the authorization the same (except for the need to be signed in
  mentioned above), but now there is a place where those things can be changed,
  making it easier to maintain an reason about.
- Keeping the UX for when a user is not authorized also the same. If not signed
  in, go to the sign in page, otherwise go to the user's profile.
- Refactoring some controllers while going through them, as well as adding some extra tests.

Still needs:
- [ ] Add tests for `UserTipsController`
- [ ] Add tests for `TipsController`
- [ ] Run this as a review app in Heroku, so that it can be tested in a staging
    environment before going live

I'm reluctant to do these things in this PR because it is already so big, but
I'd like to test it in a staging env. Do we have such an environment?

_Note:_ Please don't merge this yet. Also, I'd like to rebase before merging,
in order to add this message to the actual commit, which I feel is important.

### CODE REVIEW

**Comment by zamith** [comment]
@mzagaja All the tests are passing, but one thing that I did that I'm not sure of is that I required authentication to see or update your profile, which I believe means that guests won't be able to do it. Is this problematic? Is this how you envisioned it?

**Comment by mzagaja** [comment]
That sounds correct to me. I don't believe guests will update or change their own profiles until they convert into regular users. I will take a poke at this tomorrow, unless someone else wants to review it in the mean time. Thanks so much for all your hard work!

**Comment by mzagaja** [comment]
I received "Pundit::AuthorizationNotPerformedError in DeviseInvitable::RegistrationsController#create" when attempting to register a new user after I entered an energy bill. This was also raised when I clicked "Log In" (after pulling master to fix the Google Sign-In error). When I was already signed in from a previous session and attempted to invite someone I also received the error. /users, and /users/sign_in are the relevant paths. This is likely where we would have benefitted from some integration tests. Anyways let me know if they're working on your machine, otherwise happy to debug with you tomorrow night.

**Comment by zamith** [comment]
I will give it a look. I might have missed some check there. If I can find I'll add the tests as well.

**Comment by zamith** [comment]
Ok, I found the issue, we should not be enforcing authorization for Devise controllers. I added a test that covers that and it should all be working now.

**Comment by mzagaja** [comment]
I get the following error when attempting to adding a bill from the team leaderboard page:
screen shot 2016-08-02 at 7 52 51 pm

**Comment by mzagaja** [comment]
Also I noticed that it appears the graph data is not showing either in that view.

**Comment by zamith** [comment]
Both those things are for logged in users only, right?

**Comment by mzagaja** [comment]
The new bill error was logged in only. The second item appeared both from a logged in user perspective and also from a guest user perspective (unless I'm recalling it incorrectly, but best to check both). Though it might also be that after you made those additional commits I needed a rake db:reset.

**Comment by zamith** [comment]
Both those errors should be fixed, as well as some more subtle ones.

**Comment by mzagaja** [comment]
I merged Kathleen's pull request into master if you want to try and dissect the merge conflicts now I'll take this one next.

**Comment by zamith** [comment]
Sure, i'll look at it tomorrow. Thanks

**Comment by zamith** [comment]
@mzagaja I finally got some time to rebase this with master, sorry for taking so long.

**Comment by mzagaja** [comment]
Awesome. Working much better now. I have identified the following remaining issues:
- [x] Upload XML file lacks appropriate authorization for a user
- [x] "Next tip" button does not work.

**Comment by mzagaja** [comment]
Merged this in after fixing the bugs I found. New bugs can be filed as additional issues.

**Pull request merged**
