### PR TITLE
Eversource XML Upload - 1st pass

### PR DESCRIPTION
**Pull request by kvotolato3**
This will allow users to upload their "Download My Data" xml files from Eversource. These are files that contain the previous 12 months of meter readings and bills belonging to a particular customer.

Parsing is done with Nokogiri, and we are storing both the full xml content and jsonified content in the database. As of now, files aren't being stored anywhere.

Since I am an Eversource customer myself, I have been using a personal file to test the upload functionality. There wasn't a "Download My Data" sample file on the Green Button developer site, only the Subscription Feeds, so that's why.

Things that still need to be done after this pull request:
- Validations (we may want to use a gem for this)
- Require authentication in the controller
- Probably want to have the bills appear in the dashboard in a time series graph
- Add a link to '/uploads/new' (as of now, the user has to manually type in the url) to someplace that makes sense
- Style the Confirmation page - currently it is just a listing of the upload and the associated bills that got created from the file.

### CODE REVIEW

**Comment by kvotolato3** [comment]
I can see the Travis build is failing because when it tries to run the migration that adds the jsonb column, there is an error: 
_ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  type "jsonb" does not exist_

My first suspicion is that PostgreSQL may be out of date. I know I had to update my PostgreSQL to 9.4 (or later) before rails would let me run the migration, so maybe it is the same issue here. 

Assuming that's the issue, I think everyone needs to be aware that once we merge this, anyone who works on the app should have Postgres version 9.4 or later. 

@mzagaja Do you know how to check the Postgres version that TravisCI uses?  And, do you think we might have an issue in production?

**Comment by mzagaja** [comment]
You should be able to set it by updating .travis.yml as described at: https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version. I'll review this after you try that.

**Comment by kvotolato3** [comment]
That worked!

**Comment by mzagaja** [comment]
This looks great. As we discussed I think we're just going to make the following changes:
- Add button to team leaderboard to the upload interface
- Change the bill upload view from the text to a table
- Update the graph view to use the kWh column in the table and also make suggested updates to column names so they are appropriately descriptive

**Comment by kvotolato3** [comment]
Ready for review!

**Comment by mzagaja** [comment]
This is awesome! Great work.

**Pull request merged**
