### PR TITLE
Preliminary models, controllers

### PR DESCRIPTION
**Pull request by mahtai**
I'll leave it to other people to add the password/authentication stuff, as well as the details on what the city gave us about buildings. Energy records once we figure out if we want to use Green Button.

### CODE REVIEW

**Comment by sonya** [comment]
Thanks, this looks great. The one thing I'd like to say is about class names. Class names in Ruby conventionally are in TitleCase without underscores, so rather than `User_Building_Profile` we would conventionally use `UserBuildingProfile`.

Another thing is I find the `_profile` suffixes after all the classes to be quite verbose. I'm wondering if there's a reason you chose these names over the simpler `User`, `Team`, `Landlord` etc.

I'm not all that experienced in Ruby myself, so seasoned Rubyists please chime in as needed.

**Comment by mzagaja** [comment]
Thanks for getting at this so quickly, and also thanks to sonya for reviewing. I agree with @sonya's feedback about the naming. @mahtai would you be willing to incorporate the feedback in a new commit to this pull request?

**Comment by mahtai** [comment]
Changed as requested.

**Comment by mahtai** [comment]
Going through what Rails seems to say about its association system, I've decided to attach users to units, units to user-provided-buildings, and city-provided-buildings to landlords. We'll have to figure out what to do about user-provided and city-provided buildings at some point, but I can't see a nice way to do it right now without making the resource nesting too deep.
Also I'm not sure how to handle team association, since I think Rails wants the objects that has_many to exist for the objects that belongs_to get created, so I've left the teams out of it for the moment.

**Comment by sonya** [comment]
@mahtai, would you mind running a `rake db:migrate` so the schema file gets updated? (it's also a way to discover syntax errors in the models)

[edit] actually before that, do you have local migration files that you didn't commit to the repo?

**Pull request merged**
