### PR TITLE
Tips feedback

### PR DESCRIPTION
**Pull request by mahtai**
Added the ability to give feedback on tips. Had to completely rip out the previous tip voting system because previous attempted optimization was not robust.

### CODE REVIEW

**Comment by mzagaja** [comment]
When I tested it locally I did not see any of the feedback mechanisms. Is this pull request potentially missing changes to schema.rb and migrations that need to be checked in?

**Comment by mahtai** [comment]
Try it again now. There should be a string attribute named "feedback" on the user_tips.

**Comment by mzagaja** [comment]
Travis failed because it says the migrations haven't been executed yet. Are you sure you have pushed the latest schema.rb and run rake db:migrate?

**Comment by mahtai** [comment]
Okay, it passes now. The issue was that I'd forgotten which branch I was on.

**Pull request merged**
