### PR TITLE
Tips implement

### PR DESCRIPTION
**Pull request by mahtai**
Displays tips. 
Both logging in and pressing next button gives random new tip.
Allows for voting on tips: liked or disliked. Voting data stored as user_tips.
Disliked tips are not shown again, liked tips given the option to share, which currently does nothing.
Most user_tip code is unimportant and will be removed later.

### CODE REVIEW

**Comment by mzagaja** [comment]
Please address the failing tests flagged by Travis with a new commit. If you need help we'll poke at these on Tuesday.

**Comment by mzagaja** [comment]
Actually might have been addressed by Kathleen's commit and unrelated to your thing. I'll put this on the docket for the weekend. But now probably just needs an updated git merge from master.

**Comment by mzagaja** [comment]
This branch is not working for me when I try to sign in with Google:

screenshot 2016-06-05 13 42 55

**Comment by mahtai** [comment]
I think the error that you got was from not having any tips in your database; I think the signing in with Google should be irrelevant to the issue.

**Pull request merged**
