### PR TITLE
Sendgridfix

### PR DESCRIPTION
**Pull request by mahtai**
Much more functional version of teamjoin

### CODE REVIEW

**Comment by mahtai** [comment]
Things to check:
Current user not on a team can create a team and is listed as a team member on the team page
"Invitations" link goes to list of existing invitations for the team
"Invite a user" leads to form for an email
Test both email of a user already in the app, and an email not in the app

For user already in the app, should create an invitation
-When logged in as the receiving user, if the user is not on a team then the user page should include a link saying "Join a team" leading to list of invitations
-Hitting "Join" on an invitation should destroy the invitation, put user on the team and remove both "Join a team" and "Create a team" links on the user page.

For an email not already on the app, there might be an issue testing because we need a url for the user sign-up page, which depends on where we're hosting. But it should send that along with a token that can be used to automatically assign the user to the team that sent the invitation.
I am not completely sure how that will mesh with Devise, though.
Also the inviter variable is commented out because it complains when the inviter doesn't have a first_name and last_name assigned.

**Comment by mahtai** [comment]
The receiver-already-in-app stuff can be checked without the Sendgrid stuff, so maybe just comment out the Sendgrid stuff if you want to review that part first. Is there another mail gem that might be less of a hassle?

**Comment by mzagaja** [comment]
Currently struggling to get SendGrid working locally with .env. However I wanted to ask while I fight with this why team.rb is #team.rb#? Is there a significance to the pound signs?

**Comment by mzagaja** [comment]
The only thing left to do on this as far as I can tell is sort out the conflicts between this and the navbar which stopped working after I did the merge.

**Comment by mzagaja** [comment]
Ok I determined that master also has broken the navbar as well so I merged this in and will open a new issue for that.

**Pull request merged**
