### PR TITLE
Teamjoin

### PR DESCRIPTION
**Pull request by mahtai**
Users can create, join and leave teams. Need URL for nonusers, also everyone leaving a team should lead to the team being deleted.

### CODE REVIEW

**Comment by mzagaja** [comment]
When I go to open the main page of the app with this branch I receive an error:

screenshot 2016-03-13 18 29 45

The two merge conflicts are with Gemfile.lock and Routes.rb but those are easily resolved and not likely the source of this.

**Comment by mahtai** [comment]
Yeah, I have no idea what that error is. I thought it was just my setup not installing foundation correctly, but apparently not. I screwed with a lot of files because dev env issues.
The important stuff from my branch is all in the app folder, two migrations and the routes file. Maybe see if just using those will work.

**Comment by mahtai** [comment]
Also, if you manage to get that far, the url variable in the user mailer doesn't point anywhere because I don't know where our app is going to end up.

**Comment by mahtai** [comment]
Maybe look at the new branch sendgridfix instead. I don't know what is wrong with this one, so I cloned the master and put in the stuff that was actually useful for the team joining mechanism and also fixed some things that were still not working on my end.

**Pull request closed without merging**
