### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by ezrashim**
Added `gem jquery-turbolink` to allow turbolink to play nicely with javascript. Below are some references that I found useful: 

https://github.com/kossnocorp/jquery.turbolinks
https://github.com/zurb/foundation-sites/issues/6438

### CODE REVIEW

**Comment by mzagaja** [comment]
Given the update to schema.rb I would expect this pull request to also check-in a migration, or am I missing something?

**Comment by ezrashim** [comment]
ahhh...yes it should...except I naively git pulled origin master this morning and merged with my local branch...

**Comment by mzagaja** [comment]
git checkout the last version of the schema (git checkout HEAD~1 /path/to/schema.rb) then reset your database (rake db:reset) then create and run a new migration that does the same thing then rake db:migrate then check that in and you should be good.

**Comment by mzagaja** [comment]
I see you made new commits in attempting to fix this but you still need to `git add db/migration_name` as well to your commit to check it in for GitHub.

**Comment by mzagaja** [comment]
Ignore the comment from the referenced commit, I typed the wrong PR number by accident. Fixed with a git amend.

**Comment by mzagaja** [comment]
Just checking in to say that I see you updated this pull request last week but I'm still waiting for you to check in a migration. If you'd like I can help you with this tomorrow night.

**Comment by ezrashim** [comment]
Ill come in tonight and we can figure this out.  :)

**Pull request merged**
